---

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Set timezone to UTC
  command: timedatectl set-timezone UTC
  when: ansible_date_time.tz != 'UTC'

- name: Put /etc/hosts in place
  copy:
    src: ../files/etc.hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Enable selinux
  selinux:
    policy: targeted
    state: enforcing

- name: Disable fastestmirror plugin
  ini_file:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    section: main
    option: enabled
    value: 0
    mode: 0644
    backup: yes

- name: Install epel repository package
  package:
    name: epel-release
    state: latest

- name: Enable epel repo
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: 1
    mode: 0644
    backup: no

- name: Pre-requisite packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - bash-completion
    - bind-utils
    - bridge-utils
    - docker-latest
    - git
    - iptables-services
    - net-tools
    - pyOpenSSL
    - screen
    - strace
    - tcpdump
    - wget

- name: Disable epel repo
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: 0
    mode: 0644
    backup: no

- name: Update docker options
  lineinfile:
    dest: /etc/sysconfig/docker-latest
    backup: yes
    create: no
    state: present
    regexp: '^OPTIONS='
    line: OPTIONS='--selinux-enabled --log-driver=journald --insecure-registry 172.30.0.0/16'

- name: Restart docker
  service:
    name: docker-latest
    state: restarted
    enabled: yes

