---

- name: Setup installation pre-requisites
  include: prereqs.yml

- name: Run main OpenShift Ansible installation playbook
  include: install.yml

- name: Post installation bespoking
  include: postinstall.yml
