---

- name: Set timezone to UTC
  command: timedatectl set-timezone UTC
  when: ansible_date_time.tz != 'UTC'

- name: Put /etc/hosts in place
  copy:
    src: ../files/etc.hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Enable selinux
  selinux:
    policy: targeted
    state: enforcing

- name: Disable fastestmirror plugin
  ini_file:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    section: main
    option: enabled
    value: 0
    mode: 0644
    backup: yes

- name: Epel Repo
  package:
    name: epel-release
    state: latest

- name: Pre-requisite packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - bash-completion
    - bind-utils
    - bridge-utils
    - git
    - iptables-services
    - net-tools
    - screen
    - strace
    - tcpdump
    - wget


